export { default as AddCompanyModal } from "./AddCompanyModal/AddCompanyModal";
export { default as AddDepartmentModal } from "./AddDepartamentModal/AddDepartamentModal";
export { default as AddEmployeeModal } from "./AddEmployeeModal/AddEmployeeModal";
export { default as CompanyItem } from "./CompanyItem/CompanyItem";
export { default as DashboardListDepartament } from "./DashboardListDepartments/DashboardListDepartment";
export { default as DashboardListEmployee } from "./DashboardListEmployee/DashboardListEmployee";
export { default as DepartmentChart } from "./DepartmentChart/DepartmentChart";
export { default as EmployeeSearch } from "./EmployeeSearch/EmployeeSearch";
export { default as Login } from "./Login/LoginForm";
export { default as NavHeader } from "./NavHeader/NavHeader";
export { default as UpdateDepartmentModal } from "./UpdateDepartamentModal/UpdateDepartamentModal";
export { default as UpdateEmployeeModal } from "./UpdateEmployeeModal/UpdateEmployeeModal";
export { default as AddEmployeeToDepartment} from './AddEmployeeToDepartment/AddEmployeeToDepartment';
